### ISSUE TITLE
사용법이 불편해요!

### ISSUE THREAD

**Issue by Sangun-Kang** [red-drop/.dotfiles#1]
오! 나는 이 리포지토리를 하였다 클론! 
but 이해 할 수 없는, 사용법! 불편 too many
원한다 나는 README.md 자세한!
빠른 해결을 원합니다 
좋은 하루를! : )

**Comment by red-drop** [comment]
I am sorry, I will add setup.sh please wait. thank you for issue

**Comment by Sangun-Kang** [comment]
ok Ths~

**Comment by red-drop** [comment]
@Sangun-Kang Updated the readme https://github.com/red-drop/.dotfiles/pull/2

**Comment by red-drop** [comment]
problem Solved
